# Generated by Django 5.1.7 on 2025-03-15 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_postnote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='app_postnote.postnote')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='app_postnote.postnote')),
            ],
            options={
                'unique_together': {('source', 'target', 'link_type')},
            },
        ),
    ]
