# Generated by Django 5.1.7 on 2025-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_postnote', '0002_postnotelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnotelink',
            name='source_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('top', 'Top'), ('bottom', 'Bottom')], default='right', max_length=10),
        ),
        migrations.AddField(
            model_name='postnotelink',
            name='target_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('top', 'Top'), ('bottom', 'Bottom')], default='left', max_length=10),
        ),
    ]
