# Generated by Django 5.1.7 on 2025-03-15 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_postnote', '0004_alter_postnotelink_source_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnote',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postnote',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
