# Generated by Django 5.1.5 on 2025-03-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0204_projectboardstate_subcolumn_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboardstate',
            name='subcolumn_pair',
            field=models.CharField(blank=True, choices=[('DOING_DONE', 'Doing / Done'), ('INPROGRESS_READY', 'In Progress / Ready'), ('MVP_PERSEVERE', 'MVP / Persevere')], default='DOING_DONE', help_text='Applicable only when buffer_column is True', max_length=30, null=True),
        ),
    ]
