# Generated by Django 5.1.5 on 2025-03-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
