# Generated by Django 5.1.5 on 2025-03-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_profile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
