# Generated by Django 5.2 on 2025-04-14 04:06

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('wip_limit', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('column_type', models.CharField(choices=[('todo', 'Todo'), ('done', 'Done'), ('custom', 'Custom')], default='custom', max_length=20)),
            ],
            options={
                'verbose_name': 'Kanban Column',
                'verbose_name_plural': 'Kanban Columns',
            },
        ),
        migrations.CreateModel(
            name='MyTodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('icon', models.CharField(default='fa-list', max_length=50)),
                ('color', models.CharField(default='primary', max_length=20)),
            ],
            options={
                'verbose_name': 'Todo List',
                'verbose_name_plural': 'Todo Lists',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('canvas_x', models.IntegerField(default=0)),
                ('canvas_y', models.IntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('kanban_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='app_todos.kanbancolumn')),
                ('my_todos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='app_todos.mytodos')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_todos.todo')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
