# Generated by Django 5.2 on 2025-04-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancolumn',
            name='my_todos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columns', to='app_todos.mytodos'),
        ),
    ]
